// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmnubjyucfxlngikjhsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtbnVianl1Y2Z4bG5naWtqaHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTI0OTMsImV4cCI6MjA2NjgyODQ5M30.HxVw8QTRxzWPfmYpSNfJa9c2ar6Gtlt-RYWoEU61wXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});